Store/Controllers/AccesoController.cs
using Store.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Store.Controllers
{
    public class AccesoController : Controller
    {
        // GET: Acceso
       
        public ActionResult Login(string User,string Pass)
        {
            Variables ob = new Variables();
            try
            {
                using (Models.Data db=new Models.Data())
                {
                    var oUser = (from d in db.Usuario
                                 where d.Nickusuario == User.Trim() && d.Contra == Pass.Trim()
                                 select d).FirstOrDefault();
                   

                    if (oUser == null )
                    {
                        ViewBag.Error = "Usuario o contraseña incorrecta";
                        return View();
                    }
                   
                  

                      Session["User"] = oUser;
                }
                 return RedirectToAction("Index","Home");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
            
        }
    }
}

Store/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Store.Models;
using Store.Controllers;

namespace Store.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
           
                return View();
            
           
        }
       
    }
}

Store/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head >
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>

    <link href="~/CSS/bootstrap.css" rel="stylesheet" />
    <link href="~/CSS/normalize.css" rel="stylesheet" />
    <link href="~/CSS/Control.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="~/JS/prefixfree.min.js"></script>
    <style>
        body {
     background:#E0E4E5;
}
.category_list .category_item{
    display:block;
    width:90%;
    padding:15px 0;
    margin-bottom:20px;
    background:#E84C3D;
    text-align:center;
    text-decoration:none;
    color:#fff;
    border-radius: 10px;
}
.category_list{
    display:flex; 
    flex-direction:column; 
    width:18%;
}
.category_list .ct_item-active{
    background:#2D3E50;
}
.baddy{
   
    margin:0;
    padding:0;
    box-sizing:border-box;

}

.wrap{
    max-width:1100px;
    width:90%;
    margin:auto;
}

/*Productos*/
.products-list{
    width:82%;
    display:flex;
    flex-wrap:wrap;
}

.products-list .products-item{
    width:22%;
    margin-left:3%;
    margin-bottom:25px;
    box-shadow:0px 0px 6px 0px rgba(0,0,0,0.22);

    display:flex;
    flex-direction:column;
    align-items:center;
    align-self:flex-start;

    transition: all .4s;
}
.products-list .products-item img{
    width:100%;
}
.products-list .products-item  a{
    display:block;
    width:100%;
    padding:8px 0;
    background:#2D3E50;

    color:#fff;
    text-align:center;
    text-decoration:none;
}
    </style>
</head>
<body>
    <form >
        <div>
            <nav class="navbar navbar-expand-lg navbar-light bg-primary">
                </button>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                    <div class="dropdown">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Menu
                        </a>

                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <i color="#fff">@Html.ActionLink("Cerrar Sesion", "Login", "Acceso")</i>
                        </div>
                    </div>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                        <li class="nav-item active">
                           <input type="search" Placeholder="Buscar" />
                        </li>
                    </ul>
                    <form  class="form-inline my-2 my-lg-0">
                        
                       </form>
                </div>
            </nav>
        </div>

        <div>
            
            <div class="baddy">
                <div class="wrap">
                    <h1 style="color:#494B4D; font-weight:400;  display:flex;  flex-direction:column;  text-align:center; margin:15px 0px;">Escoge un producto</h1>
                    <div class="store-wrapper" style="display:flex;">
                        <div class="category_list" style="display:flex;  flex-direction:column;  width:18%;">
                            <a href="#" class="category_item" category="all">Todo</a>
                            <a href="#" class="category_item" category="ordenadores">Ordenadores</a>
                            <a href="#" class="category_item" category="laptops">Laptops</a>
                            <a href="#" class="category_item" category="smartphones">SmartPhones</a>
                            <a href="#" class="category_item" category="monitores">Monitores</a>
                            <a href="#" class="category_item" category="audifonos">Audifonos</a>
                        </div>
                        <section class="products-list">
                            <div class="products-item" category="laptops">
                                <img Height="167" src="~/IMG/799054-500-auto.jpg" BorderStyle="Dotted" Width="240px" />
                                <a href="">Laptop huawei</a>
                            </div>
                            <div class="products-item" category="laptops">
                                <img Height="167" src="~/IMG/882730-500-auto.jpg" BorderStyle="Dotted" Width="240px" />
                                <a href="">Laptop hp</a>
                            </div>
                            <div class="products-item" category="smartphones">
                                <img Height="167" src="~/IMG/descarga.jpg" BorderStyle="Dotted" Width="240px" />
                                <a href="">Nokia 5.3</a>
                            </div>
                            <div class="products-item" category="smartphones">
                                <img Height="167" src="~/IMG/LG.jpg" BorderStyle="Dotted" Width="240px" />
                                <a href="">Samsumg LG</a>
                            </div>
                            <div class="products-item" category="ordenadores">
                                <img Height="167" src="~/IMG/idPc.jpg" BorderStyle="Dotted" Width="240px" />
                                <a href="">Laptop hp</a>
                            </div>
                            <div class="products-item" category="ordenadores">
                                <img Height="167" src="~/IMG/PC-sobremesahp.jpg" BorderStyle="Dotted" Width="240px" />
                                <a href="">PC Asus</a>
                            </div>
                            <div class="products-item" category="monitores">
                                <img Height="167" src="~/IMG/monitorLG.jpg" BorderStyle="Dotted" Width="240px" />
                                <a href="">Monitor LG</a>
                            </div>
                            <div class="products-item" category="audifonos">
                                <img Height="167" src="~/IMG/gamerau.jpg" BorderStyle="Dotted" Width="240px" />
                                <a href="">Masacegon</a>
                            </div>
                        </section>

                    </div>
                </div>
            </div>  <br />
        </div>

        <div class="Foot">
            ™© Copyrigth -- 
            <marquee class="pro"> Contactanos al 22-7787-29 </marquee>
        </div>
        

    </form>

    <script src="~/JS/jquery-3.5.1.js"></script>
    <script src="~/JS/acciones.js"></script>
    <script src="~/JS/script.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>